apiVersion: v1
kind: Service
metadata:
  name: mysql-restaurant
  namespace: services-db
spec:
  selector:
    app: mysql-restaurant
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 31001
  type: NodePort
