spring:
  profiles:
    active: ${profile}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
    hibernate:
      ddl-auto: none # or create, create-drop, validate, none, update
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE