# JWT Secret Key
secret-key: ThisIsSSAFYEFiveIsJwtSecretKeyDoNotUseThisStatement

spring:
  datasource:
    url: jdbc:mysql://k10s210.p.ssafy.io:31004/hr?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: s210
    password: s1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: k10s210.p.ssafy.io
      port: 31008
      password: L2Srh699g86HGb53sug7XcITs
