apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-cafe
  namespace: services-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-cafe
  template:
    metadata:
      labels:
        app: mongodb-cafe
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-cafe-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-cafe-secret
                  key: password