apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: services-db
spec:
  selector:
    app: mongodb-cafe
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 31006
  type: NodePort