apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: services-db
spec:
  selector:
    app: mongo-express
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31007
  type: NodePort