apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-cafe-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/bbap-db/cafe
