image:
  debug: true

listeners:
  client:
    protocol: PLAINTEXT

externalAccess:
  enabled: true
  controller:
    service:
      type: NodePort
      nodePorts:
        - {{kafka-port}
        - {{kafka-port}
        - {{kafka-port}


controller:
  persistence:
    enabled: true
    storageClass: standard
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    mountPath: /bitnami/kafka


volumePermissions:
  enabled: true

serviceAccount:
  create: true

rbac:
  create: false


kraft:
  enabled: true
  clusterId: {{cluster-id}}

zookeeper:
  enabled: false


extraEnvVars:
  - name: KAFKA_ENABLE_KRAFT
    value: "true"
  - name: KAFKA_CFG_DELETE_TOPIC_ENABLE
    value: "true"
  - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
    value: "true"