apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: services-db
data:
  my.cnf: |
    [mysqld]
    character-set-server=utf8
    collation-server=utf8_unicode_ci
    max_connections=100
    default-time-zone='Asia/Seoul'
