apiVersion: v1
kind: Service
metadata:
  name: mysql-notification
  namespace: services-db
spec:
  selector:
    app: mysql-notification
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 31003
  type: NodePort
