apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-payment
  namespace: services-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-payment
  template:
    metadata:
      labels:
        app: mysql-payment
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: payment
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: mysql-payment-volume
              mountPath: /var/lib/mysql
            - name: mysql-config-volume
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: mysql-payment-volume
          persistentVolumeClaim:
            claimName: mysql-payment-pvc
        - name: mysql-config-volume
          configMap:
            name: mysql-config