apiVersion: v1
kind: Service
metadata:
  name: mysql-payment
  namespace: services-db
spec:
  selector:
    app: mysql-payment
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 31002
  type: NodePort
