apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-face-pvc
  namespace: services-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
