apiVersion: v1
kind: Service
metadata:
  name: mysql-face
  namespace: services-db
spec:
  selector:
    app: mysql-face
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 31005
  type: NodePort
