apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{app-name}}
  namespace: {{namespace}}
spec:
  replicas: {{replicas}}
  selector:
    matchLabels:
      app: {{app-name}}
  template:
    metadata:
      labels:
        app: {{app-name}}
    spec:
      containers:
        - name: {{app-name}}
          image: {{image-repo}}/{{app-name}}:{tag}