apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-hr
  namespace: services-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-hr
  template:
    metadata:
      labels:
        app: mysql-hr
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: hr
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: mysql-hr-volume
              mountPath: /var/lib/mysql
            - name: mysql-config-volume
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: mysql-hr-volume
          persistentVolumeClaim:
            claimName: mysql-hr-pvc
        - name: mysql-config-volume
          configMap:
            name: mysql-config