apiVersion: v1
kind: Service
metadata:
  name: mysql-hr
  namespace: services-db
spec:
  selector:
    app: mysql-hr
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 31004
  type: NodePort
