apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{middleware-name}}
spec:
  forwardAuth:
    address: "http://{{auth-service}}.{{backend-namespace}}.svc.cluster.local:{{auth-port}}/api/v1/auth/verify"
    trustForwardHeader: true
    authResponseHeaders:
      - "X-Employee-Id"