{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.pvc.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.pvc.size }}
  storageClassName: "standard"
{{- end }}