# templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ default 8080 .Values.service.targetPort }}