apiVersion: v1
kind: PersistentVolume
metadata:
  name: acme-cert-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/etc/traefik/acme"
