apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acme-cert-pvc
  namespace: traefik
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
