service:
  type: ClusterIP

ports:
  web:
    exposedPort: 80
    hostPort: 80
    protocol: TCP
    redirectTo:
      port: websecure
  websecure:
    exposedPort: 443
    hostPort: 443
    protocol: TCP

additionalArguments:
  - "--api.dashboard=true"
  - "--api.insecure=true"

logs:
  general:
    level: INFO



certResolvers:
  myresolver:
    email: {{letsencrypt-email}}
    httpChallenge:
      entryPoint: web
    storage: /etc/traefik/acme/acme.json


persistence:
  enabled: true
  name: acme-cert-pvc
  existingClaim: "acme-cert-pvc"
  accessMode: ReadWriteOnce
  size: 10Mi
  path: /etc/traefik/acme
  annotations: { }


podSecurityContext:
  fsGroupChangePolicy: "OnRootMismatch"
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
