app:
  name: {{app-name}}
  namespace: {{namespace}}
image:
  repository: {{image-repo}}
  tag: {{image-tag}}
service:
  name: {{service-name}}
  port: {{service-port}}
  targetPort: {{target-port}}
ingress:
  enabled : {{ingress-enabled}}
  name: {{ingress-name}}
  match: {{ingress-match}}
  servicePort: {{service-port}}
  certResolver: {{cert-resolver}}
replicas: {{replicas}}
persistence:
  enabled: {{persistence-enabled}}