app:
  name: {{app-name}}
  namespace: {{namespace}}
image:
  repository: {{image-repo}}
  pullPolicy: {{image-pullPolicy}}
  tag: {{image-tag}}
service:
  name: {{service-name}}
  port: {{service-port}}
  targetPort: {{target-port}}
ingress:
  enabled: {{ingress-enabled}}
  name: {{ingress-name}}
  certResolver: {{cert-resolver}}
  routes:
    - match: {{route-match}}
replicas: {{replicas}}

persistence:
  enabled: true
  volumeName: {{clf-volume-name}}
  mountPath: {{mount-path}}
  claimName: {{pvc-name}}
  pvc:
    accessMode: {{access-mode}}
    size: {{size}}
    name: {{pvc-name}}
