spring:
  profiles:
    active: ${profile}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
    hibernate:
      ddl-auto: none # or create, create-drop, validate, none, update
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

springdoc:
  packages-to-scan: com.bbap.notice.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE