spring:
  application:
      name: order_room
  profiles:
    active: ${profile}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always